name: Tests

on:
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
      working-directory: ./python/naiveautoml
    - name: Test with tox
      run: tox -e flake8 && tox -e py310 && tox -e mypy  # hereby we enable fast failures
      working-directory: ./python/naiveautoml
